version: "3.9" # optional since v1.27.0
services:
  ubuntu:
    build: ./ubuntu
    volumes:
      - ./ubuntu/volumes/opt:/opt
      - ./ubuntu/volumes/home:/home

    restart: on-failure
    command: [ "sleep", "infinity" ]
    environment:
      - name=value
