version: "3.9" # optional since v1.27.0
services:
  ubuntu:
    build: ./ubuntu
    volumes:
      - ./ubuntu/volumes/opt:/opt
      - ./ubuntu/volumes/home:/home
      # - Z:/MAINTENANCE:/MAINTENANCE
    restart: on-failure
    command: [ "sleep", "infinity" ]
    environment:
      - name=value
  db:
    image: couchbase:latest
    deploy:
      replicas: 1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./couchbase/volumes/data:/opt/couchbase/var

  server:
    build: ./simpleServer
    ports:
      - 49160:8080
    volumes:
      - ./simpleServer/volumes/server:/usr/src/app/volumes/server/
      - ./simpleServer/volumes/functions/:/usr/src/app/volumes/functions
  mealme_be:
    build: ./mealme_be
    depends_on:
      - db
    ports:
      - 5000:5000
